    /*
 * Proprietary and Confidential
 *
 * Copyright 2020 Inrupt Inc. - all rights reserved.
 *
 * Do not use without explicit permission from Inrupt Inc.
 */

const { LitVocabTerm, getLocalStore } = require("@inrupt/lit-vocab-term");
const dataFactory = require("@rdfjs/data-model");
const namedNode = dataFactory.namedNode;

/**
  Generated by artifact generator [@inrupt/lit-artifact-generator], version [0.10.5]
  as part of artifact: [vocab-solid-common], version: [0.3.2]
  at 'Tuesday, May 5, 2020 4:20 PM'.

  Vocabulary built from vocab list file: [solid-rdf-vocab/Common/Vocab-List-Solid-Common.yml].

  The Solid vocabulary providing terms (e.g. classes, properties and text strings (e.g.
 informative labels or error messages) commonly used across Solid services.
 */

function _NS(localName) {
  return (namedNode("https://inrupt.net/vocab/solid-service-common#" + localName));
}

const SOLID_SERVICE_COMMON = {
  PREFIX: "solid-service-common",
  NAMESPACE: "https://inrupt.net/vocab/solid-service-common#",
  PREFIX_AND_NAMESPACE: { "solid-service-common": "https://inrupt.net/vocab/solid-service-common#" },
  NS: _NS,



  // *******************
  // All the Literals.
  // *******************

  /**
   * Failed to process incoming message as RDF
   */
  errFailedToProcessIncomingRdf: new LitVocabTerm(
    _NS("errFailedToProcessIncomingRdf"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addMessage(`Failed to process incoming message as RDF`, "en"),

  /**
   * Incoming request validated as RDF (it contains [{{0}}] triples!)
   */
  msgRequestValidatedAsRdf: new LitVocabTerm(
    _NS("msgRequestValidatedAsRdf"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addMessage(`Incoming request validated as RDF (it contains [{{0}}] triples!)`, "en"),
  //
  // Marker allowing us put commas at the end of all lines above (only the last line does not have a comma).
  //
  END_OF_VOCAB: 'End of vocab.'
}

module.exports = SOLID_SERVICE_COMMON;
