/*
 * Proprietary and Confidential
 *
 * Copyright 2020 Inrupt Inc. - all rights reserved.
 *
 * Do not use without explicit permission from Inrupt Inc.
 */

import { LitVocabTerm, getLocalStore } from "@inrupt/lit-vocab-term";
import dataFactory from "@rdfjs/data-model";
const namedNode = dataFactory.namedNode;

/**
  Generated by artifact generator [@inrupt/lit-artifact-generator], version [0.10.5]
  as part of artifact: [vocab-core], version: [0.3.3]
  at 'Tuesday, May 5, 2020 4:18 PM'.

  Vocabulary built from vocab list file: [lit-rdf-vocab/Core/Vocab-List-LIT-Core.yml].

  The Solid vocabulary providing terms for a request body (in this case, we're really just
 providing the Named Graph details (e.g. the IRI for the named graph itself), since the contents of a request body are
 completely arbitrary.
 */

function _NS(localName: string) { 
  return (namedNode("https://w3id.org/lit/vocab/request-body#" + localName));
}

const LIT_REQUEST_BODY = {
  PREFIX: "lit-request-body",
  NAMESPACE: "https://w3id.org/lit/vocab/request-body#",
  PREFIX_AND_NAMESPACE: { "lit-request-body": "https://w3id.org/lit/vocab/request-body#" },
  NS: _NS,


  // *******************
  // All the Properties.
  // *******************

  /**
   * Test Property as we no longer support empty datasets.
   */
  testProperty: new LitVocabTerm(
    _NS("testProperty"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`Test Property as we no longer support empty datasets`, "en")
    .addComment(`Test Property as we no longer support empty datasets.`, "en"),

};

export { LIT_REQUEST_BODY };
