    /*
 * Proprietary and Confidential
 *
 * Copyright 2020 Inrupt Inc. - all rights reserved.
 *
 * Do not use without explicit permission from Inrupt Inc.
 */

const namespace = require("@rdfjs/namespace");

/**
  Generated by artifact generator [@inrupt/lit-artifact-generator], version [0.10.5]
  as part of artifact: [vocab-solid-common], version: [0.3.2]
  at 'Tuesday, May 5, 2020 4:20 PM'.

  Vocabulary built from vocab list file: [solid-rdf-vocab/Common/Vocab-List-Solid-Common.yml].

  The Solid vocabulary providing terms (e.g. classes, properties and text strings (e.g.
 informative labels or error messages) used by Solid servers at server creation time.
 */

const RDFJS_NAMESPACE = namespace("https://inrupt.net/vocab/solid-meta-server-runtime#");

const _NAMESPACE = "https://inrupt.net/vocab/solid-meta-server-runtime#";
function _NS (localName) {
  return (_NAMESPACE + localName);
}

const SOLID_META_SERVER_RUNTIME = {
  PREFIX: "solid-meta-server-runtime",
  NAMESPACE: _NAMESPACE,
  PREFIX_AND_NAMESPACE: { "solid-meta-server-runtime": "https://inrupt.net/vocab/solid-meta-server-runtime#" },
  NS: _NS,


  // *******************
  // All the Properties.
  // *******************

  /**
   * The root subject for runtime server-generated metadata.
 The idea for subject roots is that we could build up an entire graph of
 metadata (i.e. as processing progresses along a chain of processors, with each
 processor enriching this metadata with their specific metadata), and this
 term defines the root term of that graph.
   */
  subjectRoot: RDFJS_NAMESPACE("subjectRoot"),

  /**
   * Timestamp this request was received at this server.
   */
  requestReceivedTimestamp: RDFJS_NAMESPACE("requestReceivedTimestamp"),

  //
  // Marker allowing us put commas at the end of all lines above (only the last line does not have a comma).
  //
  END_OF_VOCAB: 'End of vocab.'
}

module.exports = SOLID_META_SERVER_RUNTIME;
