/*
 * Proprietary and Confidential
 *
 * Copyright 2020 Inrupt Inc. - all rights reserved.
 *
 * Do not use without explicit permission from Inrupt Inc.
 */

import { LitVocabTerm, getLocalStore } from "@inrupt/lit-vocab-term";
import dataFactory from "@rdfjs/data-model";
const namedNode = dataFactory.namedNode;

/**
  Generated by artifact generator [@inrupt/lit-artifact-generator], version [0.10.5]
  as part of artifact: [vocab-solid-common], version: [0.3.3]
  at 'Tuesday, May 5, 2020 4:20 PM'.

  Vocabulary built from vocab list file: [solid-rdf-vocab/Common/Vocab-List-Solid-Common.yml].
 */

function _NS(localName: string) { 
  return (namedNode("http://www.w3.org/ns/auth/acl#" + localName));
}

const ACL = {
  PREFIX: "acl",
  NAMESPACE: "http://www.w3.org/ns/auth/acl#",
  PREFIX_AND_NAMESPACE: { "acl": "http://www.w3.org/ns/auth/acl#" },
  NS: _NS,

  // *****************
  // All the Classes.
  // *****************

  /**
   * Any kind of access to a resource. Don't use this, use R W and RW
   */
  Access: new LitVocabTerm(
    _NS("Access"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addCommentNoLanguage(`Any kind of access to a resource. Don't use this, use R W and RW`),

  /**
   * Append accesses are specific write access which only add information, and do not remove information.
    For text files, for example, append access allows bytes to be added onto the end of the file.
    For RDF graphs, Append access allows adds triples to the graph but does not remove any.
    Append access is useful for dropbox functionality.
    Dropbox can be used for link notification, which the information added is a notification
    that a some link has been made elsewhere relevant to the given resource.
    
   */
  Append: new LitVocabTerm(
    _NS("Append"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`append`, "en")
    .addCommentNoLanguage(`Append accesses are specific write access which only add information, and do not remove information.
    For text files, for example, append access allows bytes to be added onto the end of the file.
    For RDF graphs, Append access allows adds triples to the graph but does not remove any.
    Append access is useful for dropbox functionality.
    Dropbox can be used for link notification, which the information added is a notification
    that a some link has been made elsewhere relevant to the given resource.
    `),

  /**
   * write
   */
  Write: new LitVocabTerm(
    _NS("Write"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`write`, "en"),

  /**
   * A class of agents who have been authenticated.
In other words, anyone can access this resource, but not anonymously.
The social expectation is that the authentication process will provide an
identify and a name, or pseudonym.
(A new ID should not be minted for every access: the intent is that the user
is able to continue to use the ID for continues interactions with peers,
and for example to develop a reputation)

   */
  AuthenticatedAgent: new LitVocabTerm(
    _NS("AuthenticatedAgent"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`Anyone authenticated`)
    .addCommentNoLanguage(`A class of agents who have been authenticated.
In other words, anyone can access this resource, but not anonymously.
The social expectation is that the authentication process will provide an
identify and a name, or pseudonym.
(A new ID should not be minted for every access: the intent is that the user
is able to continue to use the ID for continues interactions with peers,
and for example to develop a reputation)
`),

  /**
   * An element of access control,
    allowing agent to agents access of some kind to resources or classes of resources
   */
  Authorization: new LitVocabTerm(
    _NS("Authorization"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`authorization`)
    .addCommentNoLanguage(`An element of access control,
    allowing agent to agents access of some kind to resources or classes of resources`),

  /**
   * Allows read/write access to the ACL for the resource(s)
   */
  Control: new LitVocabTerm(
    _NS("Control"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`control`, "en")
    .addCommentNoLanguage(`Allows read/write access to the ACL for the resource(s)`),

  /**
   * An Origin is basically a web site
        (Note WITHOUT the trailing slash after the domain name and port in its URI)
        and is the basis for controlling access to data by web apps
        in the Same Origin Model of web security.
        All scripts from the same origin are given the same right.
   */
  Origin: new LitVocabTerm(
    _NS("Origin"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`Origin`)
    .addCommentNoLanguage(`An Origin is basically a web site
        (Note WITHOUT the trailing slash after the domain name and port in its URI)
        and is the basis for controlling access to data by web apps
        in the Same Origin Model of web security.
        All scripts from the same origin are given the same right.`),

  /**
   * The class of read operations
   */
  Read: new LitVocabTerm(
    _NS("Read"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`read`, "en")
    .addCommentNoLanguage(`The class of read operations`),

  // *******************
  // All the Properties.
  // *******************

  /**
   * The Access Control file for this information resource.
        This may of course be a virtual resource implemented by the access control system.
        Note also HTTP's header  Link:  foo.meta ;rel=meta can be used for this.
   */
  accessControl: new LitVocabTerm(
    _NS("accessControl"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`access control`)
    .addCommentNoLanguage(`The Access Control file for this information resource.
        This may of course be a virtual resource implemented by the access control system.
        Note also HTTP's header  Link:  foo.meta ;rel=meta can be used for this.`),

  /**
   * The information resource to which access is being granted.
   */
  accessTo: new LitVocabTerm(
    _NS("accessTo"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`to`)
    .addCommentNoLanguage(`The information resource to which access is being granted.`),

  /**
   * A class of information resources to which access is being granted.
   */
  accessToClass: new LitVocabTerm(
    _NS("accessToClass"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`to all in`)
    .addCommentNoLanguage(`A class of information resources to which access is being granted.`),

  /**
   * A person or social entity to being given the right
   */
  agent: new LitVocabTerm(
    _NS("agent"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`agent`)
    .addCommentNoLanguage(`A person or social entity to being given the right`),

  /**
   * A class of persons or social entities to being given the right
   */
  agentClass: new LitVocabTerm(
    _NS("agentClass"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`agent class`)
    .addCommentNoLanguage(`A class of persons or social entities to being given the right`),

  /**
   * A group of persons or social entities to being given the right.
          The right is given to any entity which is a vcard:member of the group,
          as defined by the document received when the Group is dereferenced.
   */
  agentGroup: new LitVocabTerm(
    _NS("agentGroup"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`agent group`)
    .addCommentNoLanguage(`A group of persons or social entities to being given the right.
          The right is given to any entity which is a vcard:member of the group,
          as defined by the document received when the Group is dereferenced.`),

  /**
   * If a resource has no ACL file (it is 404),
        then access to the resource if given by the ACL of the immediately
        containing directory, or failing that (404) the ACL of the recursively next
        containing directory which has an ACL file.
        Within that ACL file,
        any Authentication which has that directory as its acl:default applies to the
        resource. (The highest directory must have an ACL file.)

   */
  default_: new LitVocabTerm(
    _NS("default"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`default access for things in this`)
    .addCommentNoLanguage(`If a resource has no ACL file (it is 404),
        then access to the resource if given by the ACL of the immediately
        containing directory, or failing that (404) the ACL of the recursively next
        containing directory which has an ACL file.
        Within that ACL file,
        any Authentication which has that directory as its acl:default applies to the
        resource. (The highest directory must have an ACL file.)
`),

  /**
   * THIS IS OBSOLETE AS OF 2017-08-01.   See 'default'.
        Was: A directory for which this authorization is used for new files in the directory.
   */
  defaultForNew: new LitVocabTerm(
    _NS("defaultForNew"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`default access for new things in the object`)
    .addCommentNoLanguage(`THIS IS OBSOLETE AS OF 2017-08-01.   See 'default'.
        Was: A directory for which this authorization is used for new files in the directory.`),

  /**
   * Delegates a person or another agent to act on behalf of the agent.
    For example, Alice delegates Bob to act on behalf of Alice for ACL purposes.
   */
  delegates: new LitVocabTerm(
    _NS("delegates"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`delegates`, "en")
    .addCommentNoLanguage(`Delegates a person or another agent to act on behalf of the agent.
    For example, Alice delegates Bob to act on behalf of Alice for ACL purposes.`),

  /**
   * A mode of access such as read or write.
   */
  mode: new LitVocabTerm(
    _NS("mode"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`access mode`)
    .addCommentNoLanguage(`A mode of access such as read or write.`),

  /**
   * A web application, identified by its Origin, such as
        <https://scripts.example.com>, being given the right.
        When a user of the web application at a certain origin accesses the server,
        then the browser sets the Origin: header to warn that a possibly untrusted webapp
        is being used.
        Then, BOTH the user AND the origin must have the required access.
   */
  origin: new LitVocabTerm(
    _NS("origin"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`origin`)
    .addCommentNoLanguage(`A web application, identified by its Origin, such as
        <https://scripts.example.com>, being given the right.
        When a user of the web application at a certain origin accesses the server,
        then the browser sets the Origin: header to warn that a possibly untrusted webapp
        is being used.
        Then, BOTH the user AND the origin must have the required access.`),

  /**
   * The person or other agent which owns this.
    For example, the owner of a file in a filesystem.
    There is a sense of right to control.   Typically defaults to the agent who craeted
    something but can be changed.
   */
  owner: new LitVocabTerm(
    _NS("owner"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`owner`, "en")
    .addCommentNoLanguage(`The person or other agent which owns this.
    For example, the owner of a file in a filesystem.
    There is a sense of right to control.   Typically defaults to the agent who craeted
    something but can be changed.`),

};

export { ACL };
