    /*
 * Proprietary and Confidential
 *
 * Copyright 2020 Inrupt Inc. - all rights reserved.
 *
 * Do not use without explicit permission from Inrupt Inc.
 */

const $rdf = require("rdflib");

/**
  Generated by artifact generator [@inrupt/lit-artifact-generator], version [0.10.5]
  as part of artifact: [vocab-solid-common], version: [0.3.2]
  at 'Tuesday, May 5, 2020 4:20 PM'.

  Vocabulary built from vocab list file: [solid-rdf-vocab/Common/Vocab-List-Solid-Common.yml].

  The Solid vocabulary providing terms (e.g. classes, properties and text strings (e.g.
 informative labels or error messages) used by Solid servers at server creation time.
 */

const RDFLIB_NAMESPACE = new $rdf.Namespace("https://inrupt.net/vocab/solid-meta-server-creational#");

const _NAMESPACE = "https://inrupt.net/vocab/solid-meta-server-creational#";
function _NS (localName) {
  return (_NAMESPACE + localName);
}

const SOLID_META_SERVER_CREATIONAL = {
  PREFIX: "solid-meta-server-creational",
  NAMESPACE: _NAMESPACE,
  PREFIX_AND_NAMESPACE: { "solid-meta-server-creational": "https://inrupt.net/vocab/solid-meta-server-creational#" },
  NS: _NS,


    // *******************
    // All the Properties.
    // *******************

    /**
     * The root subject for creation-time server-generated metadata.
 The idea for subject roots is that we could build up an entire graph of
 metadata (i.e. as processing progresses along a chain of processors, with each
 processor enriching this metadata with their specific metadata), and this
 term defines the root term of that graph.
     */
    subjectRoot: $rdf.sym(_NS("subjectRoot")),

    /**
     * Host name of the server processing this request.
     */
    hostName: $rdf.sym(_NS("hostName")),

    /**
     * Host IP address of the server processing this request.
     */
    hostIpAddress: $rdf.sym(_NS("hostIpAddress")),

    /**
     * Timestamp this server was instantiated.
     */
    createdTimestamp: $rdf.sym(_NS("createdTimestamp")),

  //
  // Marker allowing us put commas at the end of all lines above (only the last line does not have a comma).
  //
  END_OF_VOCAB: "End of vocab."
}

module.exports = SOLID_META_SERVER_CREATIONAL;
